services:
  db:
    image: postgres
    container_name: postgres_db
    ports:
     - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: todo
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres:
